#!/usr/bin/env bash

# read -r foo
# echo "you said $foo"

# while real line loop
# while read -r line; do
#   echo "we read line : $line"
# done

while read -r line || [[ -n $line ]]; do
  echo "we read line : $line"
done
